Require C++11
Newer versions of ICU require it and the build fails on macOS otherwise
(looks like Apple’s compiler when invoked as g++ defaults to old C++
standard):

/opt/homebrew/Cellar/icu4c/70.1/include/unicode/uobject.h:134:54: error: expected ';' at end of declaration list
    static void * U_EXPORT2 operator new(size_t size) U_NOEXCEPT;
                                                     ^
                                                     ;